const members = [

  // Team 1
  { name: "Aeimpatanasuk, Kittiwat", team: 1, photo: "Team1.png" },
  { name: "Jina, Surapong", team: 1, photo: "Team1.png" },
  { name: "Anujittiwong, Juthamard", team: 1, photo: "Team1.png" },
  { name: "Chalermchaichan, Tanaporn (Kung)", team: 1, photo: "Team1.png" },
  { name: "Intanil, Nareenart", team: 1, photo: "Team1.png" },
  { name: "Weerachote, Thanarat", team: 1, photo: "Team1.png" },
  { name: "Sukseree, Manasicha", team: 1, photo: "Team1.png" },
  { name: "Chaoboonyasit, Manuschai", team: 1, photo: "Team1.png" },
  { name: "Su-Uthai, Waiwit (Gap)", team: 1, photo: "Team1.png" },
  { name: "Saksiripaisalsin, Surakiat", team: 1, photo: "Team1.png" },
  { name: "Nateesuwan, Baiyoke", team: 1, photo: "Team1.png" },
  { name: "Chokchaijaroensri, Dusit", team: 1, photo: "Team1.png" },
  { name: "Ongkhanikul, Thanapathr", team: 1, photo: "Team1.png" },
  { name: "Premsoontorn, Nithis", team: 1, photo: "Team1.png" },
  { name: "Tangsriphairoj, Sorawich", team: 1, photo: "Team1.png" },
  { name: "Skunsongbunsiri, Pakorn", team: 1, photo: "Team1.png" },
  { name: "Chanyaswad, Tatiya", team: 1, photo: "Team1.png" },
  { name: "Jaroensri, Naphat (Nook)", team: 1, photo: "Team1.png" },
  { name: "Methaapanon, Molthaya (Bee)", team: 1, photo: "Team1.png" },
  { name: "Rasri, Yukundhorn (Poom)", team: 1, photo: "Team1.png" },
  { name: "Chaijaroen, Jirachai", team: 1, photo: "Team1.png" },

  // Team 2
  { name: "Apimonbutra, Jarumart", team: 2, photo: "Team2.png" },
  { name: "Atiptamvaree, Eakong", team: 2, photo: "Team2.png" },
  { name: "Chomchalerm, Gunta (Parn)", team: 2, photo: "Team2.png" },
  { name: "Kamnirdsittiseree, Thanapon (Boss)", team: 2, photo: "Team2.png" },
  { name: "Klamkham, Kornhathai (Off)", team: 2, photo: "Team2.png" },
  { name: "Korkijrattanakul, Nakin", team: 2, photo: "Team2.png" },
  { name: "Kunopagarnwong, Supawit (Film)", team: 2, photo: "Team2.png" },
  { name: "Limprapakornchai, Nattapong", team: 2, photo: "Team2.png" },
  { name: "Morrodkute, Gessarin", team: 2, photo: "Team2.png" },
  { name: "Pongluangtham, Pat", team: 2, photo: "Team2.png" },
  { name: "Prananpaeng, Sutthiphan", team: 2, photo: "Team2.png" },
  { name: "Prasitsirikul, Anchana", team: 2, photo: "Team2.png" },
  { name: "Prompunjai, Pitchaya", team: 2, photo: "Team2.png" },
  { name: "Puengmai, Duangruetai", team: 2, photo: "Team2.png" },
  { name: "Rekathitasret, Nonpakorn (Ahm)", team: 2, photo: "Team2.png" },
  { name: "Sahasinthop, Patcharamai Eugene", team: 2, photo: "Team2.png" },
  { name: "Singhrakthai, Roselyn", team: 2, photo: "Team2.png" },
  { name: "Songnui, Siri-Apa (Mein)", team: 2, photo: "Team2.png" },
  { name: "Sunthonchanya, Vittaya", team: 2, photo: "Team2.png" },
  { name: "Teerapattanasiri, Witiwat", team: 2, photo: "Team2.png" },
  { name: "Thongchaigullit, Vasin", team: 2, photo: "Team2.png" },

  // Team 3
  { name: "Jariyanantakul, Wassaphorn", team: 3, photo: "Team3.png" },
  { name: "Mallikamas, Nanthachat", team: 3, photo: "Team3.png" },
  { name: "Tipayamahing, Keowalee", team: 3, photo: "Team3.png" },
  { name: "Prapapunsiri, Apichaya", team: 3, photo: "Team3.png" },
  { name: "Chitpanich, Sukanya", team: 3, photo: "Team3.png" },
  { name: "Chunchatchawan, Kanidtha", team: 3, photo: "Team3.png" },
  { name: "Rodwattanakul, Yosita", team: 3, photo: "Team3.png" },
  { name: "Limsomkiat, Panchanit", team: 3, photo: "Team3.png" },
  { name: "Suratanasurang, Wattakorn (Bank)", team: 3, photo: "Team3.png" },
  { name: "Ariyadej, Pranpreeya (Jeab)", team: 3, photo: "Team3.png" },
  { name: "Changsnit, Papitchaya (Aoey)", team: 3, photo: "Team3.png" },
  { name: "Patanaponganan, Nisa", team: 3, photo: "Team3.png" },
  { name: "Ditsuwan, Kittidech", team: 3, photo: "Team3.png" },
  { name: "Kongkai, Napan", team: 3, photo: "Team3.png" },
  { name: "Phornngam, Jitlada", team: 3, photo: "Team3.png" },
  { name: "Boonperm, Phasin", team: 3, photo: "Team3.png" },
  { name: "Chuensawang, Orapan", team: 3, photo: "Team3.png" },
  { name: "Jiamwijitkul, Siripong", team: 3, photo: "Team3.png" },
  { name: "Chalong, Sasithorn", team: 3, photo: "Team3.png" },
  { name: "Sa-nguanjin, Pornthip", team: 3, photo: "Team3.png" },
  { name: "Lomsathiean, Pa-Or", team: 3, photo: "Team3.png" },

  // Team 4
  { name: "Wimonthammawat, Witchuda", team: 4, photo: "Team4.png" },
  { name: "Limwattananond, Wanwadee", team: 4, photo: "Team4.png" },
  { name: "Visetpromsri, Kanyarat", team: 4, photo: "Team4.png" },
  { name: "Taveekarn, Waran", team: 4, photo: "Team4.png" },
  { name: "Lokwipas, Peerayos", team: 4, photo: "Team4.png" },
  { name: "Piboonkulsamrit, Manussavee", team: 4, photo: "Team4.png" },
  { name: "Bhongsudhep, Thanaphon", team: 4, photo: "Team4.png" },
  { name: "Pantrakarn, Nattachat (Kim)", team: 4, photo: "Team4.png" },
  { name: "Suttivorayanon, Kitti (Bank)", team: 4, photo: "Team4.png" },
  { name: "Siphairoch, Yonratond Punch", team: 4, photo: "Team4.png" },
  { name: "Jungrungruang, Pornthip", team: 4, photo: "Team4.png" },
  { name: "Arunaramwong, Ajchariya", team: 4, photo: "Team4.png" },
  { name: "Roongruangmanirat, Vijcha (Big)", team: 4, photo: "Team4.png" },
  { name: "Tapaneeyangkul, Yuwadee (Puiz)", team: 4, photo: "Team4.png" },
  { name: "Pornruttanapun, Chaiyot", team: 4, photo: "Team4.png" },
  { name: "Udomsrisuk, Wipoosit", team: 4, photo: "Team4.png" },
  { name: "Punthawornwong, Chotipong (Fame)", team: 4, photo: "Team4.png" },
  { name: "Sae-lao, Rinradee", team: 4, photo: "Team4.png" },
  { name: "Wongsiridachakoon, Sahapon (Brandy)", team: 4, photo: "Team4.png" },
  { name: "Ritthatham, Chanin", team: 4, photo: "Team4.png" },
  { name: "Narongphan, Chawalwit Kong", team: 4, photo: "Team4.png" },

  // Team 5
  { name: "Kwandee, Pinbhan", team: 5, photo: "Team5.png" },
  { name: "Lumyai, Kantipa (Poy)", team: 5, photo: "Team5.png" },
  { name: "Jaraspankul, Nuttapol", team: 5, photo: "Team5.png" },
  { name: "Gertphol, Sopitjariya", team: 5, photo: "Team5.png" },
  { name: "Paiboonpinyalert, Metha", team: 5, photo: "Team5.png" },
  { name: "Kanjanakaroon, Jaturont", team: 5, photo: "Team5.png" },
  { name: "Wongtanom, Supanut", team: 5, photo: "Team5.png" },
  { name: "Ocharos, Chanunya", team: 5, photo: "Team5.png" },
  { name: "Poonpipatnun, Titaya", team: 5, photo: "Team5.png" },
  { name: "Jintanachaiwat, Werapat", team: 5, photo: "Team5.png" },
  { name: "Coasol, Natnicha", team: 5, photo: "Team5.png" },
  { name: "Korpakdeesirikul, Thanapong (Art)", team: 5, photo: "Team5.png" },
  { name: "Seedang, Nantatchaporn (Kwan)", team: 5, photo: "Team5.png" },
  { name: "Linder, Alissara", team: 5, photo: "Team5.png" },
  { name: "Kiwatthana, Siriporn (New)", team: 5, photo: "Team5.png" },
  { name: "Triamwiriyakul, Napat", team: 5, photo: "Team5.png" },
  { name: "Buapan, Kanchana", team: 5, photo: "Team5.png" },
  { name: "Dusitanont, Piriya", team: 5, photo: "Team5.png" },
  { name: "Pordi, Panida", team: 5, photo: "Team5.png" },
  { name: "Rodkean, Ponpithak", team: 5, photo: "Team5.png" },
  { name: "Ngamkam, Pakin", team: 5, photo: "Team5.png" },

  // Team 6
  { name: "Nilwanna, Panita", team: 6, photo: "Team6.png" },
  { name: "Rattanaket, Weeraporn", team: 6, photo: "Team6.png" },
  { name: "Ngammuang, Natuchkamon (Ryu)", team: 6, photo: "Team6.png" },
  { name: "Sukrot, Charana", team: 6, photo: "Team6.png" },
  { name: "Teja-Isavadharm, Ekkachat (Nueng)", team: 6, photo: "Team6.png" },
  { name: "Vasuvudhiroch, Dararin", team: 6, photo: "Team6.png" },
  { name: "Maytheedol, Muen", team: 6, photo: "Team6.png" },
  { name: "Peerabool, Tritaporn (Jub)", team: 6, photo: "Team6.png" },
  { name: "Sermsiriwiwat, Nantawan (Putt)", team: 6, photo: "Team6.png" },
  { name: "Vongvitavat, Tree", team: 6, photo: "Team6.png" },
  { name: "Paiboonrattanakorn, Pathom (Joe)", team: 6, photo: "Team6.png" },
  { name: "Srithongsook, Chanon", team: 6, photo: "Team6.png" },
  { name: "Tantimeth, Sirin", team: 6, photo: "Team6.png" },
  { name: "Nithisansawadikul, Sasiwimon", team: 6, photo: "Team6.png" },
  { name: "Taycharpipranai, Nattinee (Fah)", team: 6, photo: "Team6.png" },
  { name: "Wuttivichayanun, Pakorn", team: 6, photo: "Team6.png" },
  { name: "Pipatphuriwat, Natthakritta (Kik)", team: 6, photo: "Team6.png" },
  { name: "Bijaphala, Kamalin", team: 6, photo: "Team6.png" },
  { name: "Klinla-Or, Tharathep (Fill)", team: 6, photo: "Team6.png" },
  { name: "Maraprasertsak, Narat", team: 6, photo: "Team6.png" },
  { name: "Tangphongsaphan, Pattanee", team: 6, photo: "Team6.png" },

  // Team 7
  { name: "Kositsrikunakorn, Kosit", team: 7, photo: "Team7.png" },
  { name: "Mard-Arhin, Amareena", team: 7, photo: "Team7.png" },
  { name: "Keongamaroon, Thongchai (Tong)", team: 7, photo: "Team7.png" },
  { name: "Payakkachon, Krittamate (Champ)", team: 7, photo: "Team7.png" },
  { name: "Piyapanyapong, Nicha", team: 7, photo: "Team7.png" },
  { name: "Tiatasin, Natthanan (Elle)", team: 7, photo: "Team7.png" },
  { name: "Sasuwan, Thapanee", team: 7, photo: "Team7.png" },
  { name: "Tangmanpakdeepong, Vee", team: 7, photo: "Team7.png" },
  { name: "Tantanasarid, Warut", team: 7, photo: "Team7.png" },
  { name: "Mahachassada, Sang", team: 7, photo: "Team7.png" },
  { name: "Chalakornsuprada, Thepthipthong", team: 7, photo: "Team7.png" },
  { name: "Pipatchaisiri, Patom", team: 7, photo: "Team7.png" },
  { name: "Srisuwan, Patcharee", team: 7, photo: "Team7.png" },
  { name: "Roengsamut, Boonsita (Mook)", team: 7, photo: "Team7.png" },
  { name: "Onmee, Budnampetch (Praew)", team: 7, photo: "Team7.png" },
  { name: "Yudhasompop, Ammar", team: 7, photo: "Team7.png" },
  { name: "Sutheerawong, Tinnaphat", team: 7, photo: "Team7.png" },
  { name: "Laohawanich, Lucksamon (Palm)", team: 7, photo: "Team7.png" },
  { name: "Chaisuntornsiri, Acharawan Nui", team: 7, photo: "Team7.png" },
  { name: "Khunprom, Somchanok", team: 7, photo: "Team7.png" },

  // ... Teams 8–16 are included in the same generated file ...

  // Team 17
  { name: "Thongtua, Wantanee (Eve)", team: 17, photo: "Team17.png" },
  { name: "Tannapaiboon, Anyarat", team: 17, photo: "Team17.png" },
  { name: "Bijaphala, Panitan", team: 17, photo: "Team17.png" },
  { name: "Kittisakpiruch, Hame (Mae)", team: 17, photo: "Team17.png" },
  { name: "Voravetsakul, Varis", team: 17, photo: "Team17.png" },
  { name: "Karunyakorn, Jirachote", team: 17, photo: "Team17.png" },
  { name: "Sasipaphanuwat, Natsasi", team: 17, photo: "Team17.png" },
  { name: "Chokratanachai, Wanlert (Ice)", team: 17, photo: "Team17.png" },
  { name: "Leelasathapornkun, Thanapar (Ball)", team: 17, photo: "Team17.png" },
  { name: "Amnutkittikul, Nuttakul (OAT)", team: 17, photo: "Team17.png" },
  { name: "Rochanakee, Porntipa", team: 17, photo: "Team17.png" },
  { name: "Kittikanjanapa, Sanit", team: 17, photo: "Team17.png" },
  { name: "Piromnin, Natdabhorn", team: 17, photo: "Team17.png" },
  { name: "Tantiyapinun, Tummasorn", team: 17, photo: "Team17.png" },
  { name: "Sundarabhogin, Nathaphop", team: 17, photo: "Team17.png" },
  { name: "Oonhawat, Juthamas", team: 17, photo: "Team17.png" },
  { name: "Wutthiprechachan, Jackrit", team: 17, photo: "Team17.png" },
  { name: "Saritdichainunta, Rungnapa", team: 17, photo: "Team17.png" },
  { name: "Sawaengpobsook, Suttichai", team: 17, photo: "Team17.png" },
  { name: "Chanyaswad, Pradubyos", team: 17, photo: "Team17.png" },

  // Team 18
  { name: "Kulnimit, Pantamit", team: 18, photo: "Team18.png" },
  { name: "Ngamcharoen, Ratthapoom (Pond)", team: 18, photo: "Team18.png" },
  { name: "Thaivorasit, Trungta", team: 18, photo: "Team18.png" },
  { name: "Horputra, Pinkaew", team: 18, photo: "Team18.png" },
  { name: "Udompol, Chalermrat (Art)", team: 18, photo: "Team18.png" },
  { name: "Dechnarong, Supakan (Pang)", team: 18, photo: "Team18.png" },
  { name: "Chusaksri, Chupong", team: 18, photo: "Team18.png" },
  { name: "Laempetch, Pornpol (Gunn)", team: 18, photo: "Team18.png" },
  { name: "Chatroopracheewin, Arparat (May)", team: 18, photo: "Team18.png" },
  { name: "Ruangrong, Kasama", team: 18, photo: "Team18.png" },
  { name: "Nirojsil, Noppadet", team: 18, photo: "Team18.png" },
  { name: "Siriwong, Kornkrit", team: 18, photo: "Team18.png" },
  { name: "Wangaree, Adisak", team: 18, photo: "Team18.png" },
  { name: "Thamjarat, Thanyavit Tan", team: 18, photo: "Team18.png" },
  { name: "Kositsrikunakorn, Tanit (Kiak)", team: 18, photo: "Team18.png" },
  { name: "Kongthongluck, Prang", team: 18, photo: "Team18.png" },
  { name: "Chuangchai, Karittha", team: 18, photo: "Team18.png" },
  { name: "Promkittipas, Supasasapon (CP)", team: 18, photo: "Team18.png" },
  { name: "Komasmalai, Jaranya", team: 18, photo: "Team18.png" },
  { name: "Kraisangka, Thansuda Fueng", team: 18, photo: "Team18.png" },

  // Team 19
  { name: "Srimungkla, Thidarat Yok", team: 19, photo: "Team19.png" },
  { name: "Kamma, Pipat", team: 19, photo: "Team19.png" },
  { name: "Kaewwisetkul, Punjapon", team: 19, photo: "Team19.png" },
  { name: "Todaechavattana, Mattana", team: 19, photo: "Team19.png" },
  { name: "Jaichoom, Oranich (Nan)", team: 19, photo: "Team19.png" },
  { name: "Yangyuen, Att", team: 19, photo: "Team19.png" },
  { name: "Danvittayakorn, Supaporn", team: 19, photo: "Team19.png" },
  { name: "Amornwat, Wipawee (Sugar)", team: 19, photo: "Team19.png" },
  { name: "Kosubpaisarn, Siriporn", team: 19, photo: "Team19.png" },
  { name: "Logavit, Salinkate", team: 19, photo: "Team19.png" },
  { name: "Bhundhoombhoad, Pakkawat (Map)", team: 19, photo: "Team19.png" },
  { name: "Tantipanichkul, Kanokwan", team: 19, photo: "Team19.png" },
  { name: "Kitikannakorn, Kamolrat (Kung)", team: 19, photo: "Team19.png" },
  { name: "Amnuayviriya, Issaree", team: 19, photo: "Team19.png" },
  { name: "Bangboonrit, Chalinee (Amy)", team: 19, photo: "Team19.png" },
  { name: "Chanthapeth, Pichamon", team: 19, photo: "Team19.png" },
  { name: "Saynatee, Prin", team: 19, photo: "Team19.png" },
  { name: "Thanadka, Nontaporn", team: 19, photo: "Team19.png" },
  { name: "Seemakhup, Skundech", team: 19, photo: "Team19.png" },
  { name: "Wongsrisakul, Bhurinuth (Poom)", team: 19, photo: "Team19.png" },

  // Team 20
  { name: "Wongaree, Tantawan", team: 20, photo: "Team20.png" },
  { name: "Vachirapipop, Malika (Ka)", team: 20, photo: "Team20.png" },
  { name: "Raksasiripong, Naruemon", team: 20, photo: "Team20.png" },
  { name: "Phasut, Sirapob", team: 20, photo: "Team20.png" },
  { name: "Thasanthiah, Saruta", team: 20, photo: "Team20.png" },
  { name: "Pituxcoosuvarn, Apinya", team: 20, photo: "Team20.png" },
  { name: "Ruangratchaneekorn, Sarayuth", team: 20, photo: "Team20.png" },
  { name: "Amornpitakwong, Thanchida", team: 20, photo: "Team20.png" },
  { name: "Nakphairat, Chanvit", team: 20, photo: "Team20.png" },
  { name: "Sorosthunyapong, Peerawat", team: 20, photo: "Team20.png" },
  { name: "Hasunaha, Phenphan", team: 20, photo: "Team20.png" },
  { name: "Muangpan, Onanong", team: 20, photo: "Team20.png" },
  { name: "Dhanuwongkarnkar, Chayut", team: 20, photo: "Team20.png" },
  { name: "Keawraing, Watthana", team: 20, photo: "Team20.png" },
  { name: "Khunchotiphong, Saranya (Lyn)", team: 20, photo: "Team20.png" },
  { name: "Tejapijaya, Najpol", team: 20, photo: "Team20.png" },
  { name: "Jiraalongkorn, Wutthakarn", team: 20, photo: "Team20.png" },
  { name: "Tangtorkit, Surawadee", team: 20, photo: "Team20.png" },
  { name: "Intasen, Phadtanaporn (Fai)", team: 20, photo: "Team20.png" },
  { name: "Sihanatkathakul, Poomkawin", team: 20, photo: "Team20.png" }

];